site_name: Hymn | Learn
theme:
    name: readthedocs
    highlightjs: true
nav:
    - Home: index.md
    - About: about.md
    - Learn By Example:
        - Introduction: learn-by-example/introduction.md
        - Hello World: learn-by-example/hello_world.md
        - Primitives: learn-by-example/primitives.md
        - Conditionals: learn-by-example/conditionals.md
        - Classes: learn-by-example/classes.md
        - Enums: learn-by-example/enums.md
        - Interfaces: learn-by-example/interfaces.md
        - Matching: learn-by-example/matching.md
        - Built In Functions: learn-by-example/built-in-functions.md
        - Casting: learn-by-example/casting.md
    - Book:
        - Introduction: book/introduction.md
        - Getting Started: book/getting_started.md
