site_name: Hymn | Learn
theme:
    name: readthedocs
    highlightjs: true
nav:
    - Home: index.md
    - About: about.md
    - Learn By Example:
        - Introduction: examples/introduction.md
        - Hello World: examples/hello_world.md
        - Conditionals: examples/conditionals.md
        - Classes: examples/classes.md
        - Enums: examples/enums.md
        - Interfaces: examples/interfaces.md
        - Matching: examples/matching.md
        - Try + Catch: examples/try_catch.md
    - Book:
        - Introduction: book/introduction.md
        - Getting Started: book/getting_started.md
        - Primitives: book/primitives.md
        - Casting: book/casting.md
        - Built In Functions: book/built-in-functions.md
